[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { path = "../config" }
controller = { path = "../controller" }
db = { path = "../db" }
http = { path = "../http" }
model = { path = "../model" }
view = { path = "../view" }
ws = { path = "../ws" }
