[package]
name = "db"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }

[dev-dependencies]
tempfile = "3.10"
